### ISSUE TITLE
Improve the UI of the login page and update the meta details for enhanced SEO

### ISSUE THREAD

**Issue by Sunscar-Sony** [artizticamit/i-book-social-media-website-#21]
We can focuses on revamping the login page's user interface to create a more intuitive and visually appealing experience. Alongside this, we will update the meta details to boost search engine optimization, ensuring better visibility and improved user engagement.

**Comment by artizticamit** [comment]
That seems a good idea @Sunscar-Sony , if you want you could work on it.

**Comment by Sunscar-Sony** [comment]
Ready to work on it!
