### ISSUE TITLE
Add navbar to Saved Posts Page

### ISSUE THREAD

**Issue by artizticamit** [artizticamit/i-book-social-media-website-#23]
Need to add navigation bar on the saved posts page.

**Comment by MrunalKashid02** [comment]
can i work on this issue

**Comment by artizticamit** [comment]
Sure @MrunalKashid02, for the setup use docker, otherwise you have to create your own mongoDB URL in mongo atlas.
I am assigning this issue to you.

**Comment by MrunalKashid02** [comment]
Then there must be env file for backend as well right ?

**Comment by artizticamit** [comment]
Yes, but can't share that is sensitive information.

**Comment by MrunalKashid02** [comment]
No i doesn't mean that but I got the file env which save as env example for backend in repo.

**Comment by artizticamit** [comment]
that is just an example for showing environment variables name present in the project. Because in the project those env variables are used and the contributors needs to know about it, otherwise they have to search through whole project.
You could prefer to docker implementation that will be more easy to setup locally.

**Comment by MrunalKashid02** [comment]
Yeah. That why I am asking for env file with only env variables not with value or url. I knew that security purpose no one can share mongo url.

**Comment by artizticamit** [comment]
Yes, that is the purpose of .env.example file, you create your own .env file and just take the variables name from .env.example file.

**Comment by MrunalKashid02** [comment]
I setup the workspace and database connected but getting this error while 

![Screenshot 2024-10-20 190728](https://github.com/user-attachments/assets/1f58e708-9b9d-4723-a860-df1fcc290a04)
![Screenshot 2024-10-20 190704](https://github.com/user-attachments/assets/e4b8d1de-9ff2-4c99-8e81-f085d705f397)

i couldnt able to figure out what kind of error is this.

**Comment by artizticamit** [comment]
Ok let me check it, I will update in a half an hour.
