### ISSUE TITLE
Working hamburger

### ISSUE THREAD

**Issue by artizticamit** [artizticamit/i-book-social-media-website-#24]
Need to add logic for the working hamburger for the side panel.
![image](https://github.com/user-attachments/assets/8c042241-e548-403e-b409-9536764e41cb)

**Comment by kushchoudhary98** [comment]
I can work on that.

**Comment by artizticamit** [comment]
Ok @kushchoudhary98 , I am assigning this to you, use Docker if possible to setup otherwise you have to setup your own mongodb url.
