### ISSUE TITLE
Enhance Upload button UI

### ISSUE THREAD

**Issue by artizticamit** [artizticamit/i-book-social-media-website-#25]
Need to enhance UI of the upload button in the profile section of the user.
Currently it is just plain white.
Please prepare some mockups to be reviewed, before working on this.
All ideas are welcome.
![image](https://github.com/user-attachments/assets/a80e1d7a-367e-494d-945c-4a213532b21a)

**Comment by Dungho123d** [comment]
Hi @artizticamit  , I'd like to help with this issue. Could you please assign it to me?

**Comment by artizticamit** [comment]
Ok @Dungho123d , Ping me in linkedin.

**Comment by Dungho123d** [comment]
Hey there! I reconfigured the profile.css file to improve the Upload button UI and this is the result. If you are unsatisfied or have any suggestions, please give me a reply. Thank you!
![update_buttonUpload](https://github.com/user-attachments/assets/650d62fb-9a5e-4b58-bda9-8d3886744928)

**Comment by artizticamit** [comment]
Nice work and sorry for the delay, seems nice design to me.
You could raise a PR in develop branch

**Comment by Dungho123d** [comment]
I haved make a PR in develop branch.
Please check it and give me a feedback.
