### ISSUE TITLE
[BUG]: Profile pic not updating on new image upload

### ISSUE THREAD

**Issue by artizticamit** [artizticamit/i-book-social-media-website-#27]
The profile picture is not updated in this particular section when a new image is uploaded.
![image](https://github.com/user-attachments/assets/46ac7031-590c-413d-908b-e1552d9d733b)
Repro Steps:
1. Go to profile section of the user
2. Upload new profile picture
3. Can wait for a min or just refresh, other pictures will asynchronously will update, but this components profile pic doesn't update.

**Comment by devarsh10** [comment]
Hello @artizticamit, I have worked on this issue. May I raise a PR mentioning this issue? OR give the description that what changes I have made.


Thank You.
Warm Regards,
Devarsh.

**Comment by artizticamit** [comment]
Yes please if you are done with it, you could raise the PR.

**Comment by devarsh10** [comment]
Hello @artizticamit, 
I have raised PR #42. Can you please verify if there's any mistake? I read the guidelines, though, and then raised the PR. But it would be beneficial if you confirmed.

Thank you.

**Comment by artizticamit** [comment]
Nice work, seems all working fine.
