### ISSUE TITLE
Enhance README file 

### ISSUE THREAD

**Issue by artizticamit** [artizticamit/i-book-social-media-website-#33]
Need to enhance README file for this repo, so that, there are proper sections as mentioned.
1. Project title
2. Project description
3. Table of contents
4. Installation guide
5. Features
6. Contributing (should mention for develop branch for contributing only, no cloning or forking of master branch)
7. Acknowledgements

**Comment by JollyJolli** [comment]
Hey there! Assing me please.

**Comment by artizticamit** [comment]
@JollyJolli , you could update it. I will review it tomorrow. Thank you for your time.

**Comment by JollyJolli** [comment]
Have a nice sleep!

**Comment by artizticamit** [comment]
Have merged those, changes, but need some changes. Needed two sections for installation guide, one for cloning and doing npm install and npm run, another cloning and doing docker build (not docker compose), could refer to previous commits changes to see the steps.

**Comment by JollyJolli** [comment]
Perfect, I will make it in some minutes.

**Comment by artizticamit** [comment]
Any update on this?

**Comment by JollyJolli** [comment]
i forgot ☠ I will do it rn

**Comment by artizticamit** [comment]
No Issue, and thanks man.
