### ISSUE TITLE
[UI Issue]: The Login and Signup pages are not alike

### ISSUE THREAD

**Issue by Abhishek14104** [artizticamit/i-book-social-media-website-#36]
![WhatsApp Image 2024-10-22 at 7 01 13 PM](https://github.com/user-attachments/assets/fb408714-1b4f-43ec-a957-1d0f3f5a063b)
![WhatsApp Image 2024-10-22 at 7 01 12 PM](https://github.com/user-attachments/assets/6183b701-0b0c-4ab3-952f-3fb3e33a54e8)

The Login and Signup pages are completely different which makes the User experience a little weird.

I will like to work on this issue.

**Comment by artizticamit** [comment]
Closing this issue, already such issue created. Thanks
